### PR TITLE
Added Application Modal Response

### PR DESCRIPTION
**Pull request by Taimoor-Tariq**
Added response types for Application Modals

### CODE REVIEW

**Comment by shaydewael** [comment]
@Taimoor-Tariq The added types and enum values look good 👍 

While `ModalBuilder` seems like it could be really helpful, this package is intended to be a lighter interface so it's probably not the best project for it. However, would still like to merge the rest of your PR if you're open to removing the `ModalBuilder`-specific code.

**Comment by Taimoor-Tariq** [comment]
Sure I can remove the `ModalBuilder`

**Comment by Taimoor-Tariq** [comment]
Yea I totally missed that, it should be fixed now

**Comment by shaydewael** [comment]
thanks @Taimoor-Tariq—looks good 👍

**Pull request merged**
